use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'MARSDKCore_ios_Example' do
  pod 'MARSDKCore_ios', :path => '../'

  target 'MARSDKCore_ios_Tests' do
    inherit! :search_paths

    
  end
end
